# .github/workflows/update-activity.yml:

name: Update GitHub Activity

on:
  schedule:
    - cron: "*/30 * * * *" # Runs every 30 minutes
  workflow_dispatch: # Allows manual triggering

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update GitHub Activity
        uses: yongyuebj4/activity-log-yue@t5t
        with:
          GITHUB_USERNAME: "yongyuebj4"
          GITHUB_TOKEN: ${{ secrets.ACTIONSECRET_2024 }} # Ensure this matches the secret name in repository settings
          TARGET REPOS: " [yue-software-development/ponyta2-day]"
          EVENT_LIMIT: '100'
